### ISSUE TITLE
평야구매가 안됨.

### ISSUE THREAD

**Issue by shdudwns** [Potatoshare88/PSArea#21]
/buyfield id 하면  Doesn't Exist만 계속 됩니다.
그리고 /makeland하면 땅번호가 떠야하는데 안떠서 모르겠고, 이동하면 이상한대로 이동합니다.

**Comment by shdudwns** [comment]
@Potatoshare88

**Comment by Potatoshare88** [comment]
일단 필드같은 경우는 등록 방식이 플레이어 움직임 감지해서 그 등록 좌표면 등록하는 형식인데 그 점은 수정하려 하였고요.
/makeland 땅 번호 뜨지 않는 것은 수정하겠으며
이동은 제대로 될 텐데요?(테스트 함)

**Comment by nnnlog** [comment]
@Potatoshare88 /makeland 등 땅 구매/생성 등은 자동으로 해주세요

**Comment by Potatoshare88** [comment]
@nnnlog 일단 Field와 Land는 매우 다릅니다;;(Field는 평야, Land는 일반 영역(섬, 평야 제외하고 아무데서나 생성 가능))
Field를 말하시는 것이면 현재 생각중입니다.
추가를 최대한 빨리 하면 좋겠지만 일단 첫번째로는 등록을 어떻게 할지부터 문제인데.. 계속 무한대로 생겨나다 보니 한줄 끝내고 다른 한줄하는 것이 불.가.능 합니다.(한줄만 계속 등록되는 현상 발생)
그렇다고 x쪽으로 한땅 z쪽으로 한땅 가게 하는 것은 제가 하기 힘듭니다.(하지만 알고리즘을 계속 짜고 있죠.)
이 부분에 대한 도움이 필요합니다.

**Comment by Potatoshare88** [comment]
추가 하자면 원래는 Chunk가 로드 될시 해당하는 좌표값을 기준으로 생성하는 방식도 고려하였지만 Generator의 populateChunk를 AsyncTask로 돌려서 좌표값을 등록할 때 문제가 생기면서 Task가 멈춥니다.(와우..)
그 전에는 그냥 클래스를 가져오려 했는데 그건 안 되고 그렇다고 Server::getInstance()로 가져오려는데 너무 메모리가 큰 클래스라서 가져오면 터지는 매우 매우 망할 현상입니다.

**Comment by nnnlog** [comment]
@Potatoshare88 /makeland의 경우에는 딱 하나만 생성을 해주세요.

**Comment by Potatoshare88** [comment]
@nnnlog 일단 대체 어떤 생각으로 하나만 생성이 안 된다고 생각하는지;; /makeland는 딱 하나만 생성합니다. 다수가 아니라;;
