### ISSUE TITLE
자신의 섬인데 모든 이벤트가 캔슬됩니다

### ISSUE THREAD

**Issue by shdudwns** [Potatoshare88/PSArea#8]
월드보호가 너무너무 잘되네요..ㅜㅜ
그리고 /setprotectworld 한번더 치면 월드보호 비활성화 될까요?

**Comment by Potatoshare88** [comment]
잠시만요 테스트 할께요

**Comment by Potatoshare88** [comment]
그리고 /setprotectworld [Levelname] [true or false]로 하시면 됩니다.
테스트 결과 잘 작동 되는데요...?

**Comment by shdudwns** [comment]
@Potatoshare88 op를 빼고 테스트 하셨나요?

**Comment by shdudwns** [comment]
setprotectworld아직 비활성화가 없는데요?

**Comment by nnnlog** [comment]
@Potatoshare88 true/false는 없고 true만 있음
